services:
  mc:
    image: itzg/minecraft-server
    container_name: ${PROJECT_NAME}-mc
    stdin_open: true
    tty: true
    ports:
      - "0.0.0.0:25565:25565"
    environment:
      EULA: "true"
      MODPACK_PLATFORM: ${MODPACK_PLATFORM}
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: ${CF_PAGE_URL}
      CF_FILENAME_MATCHER: ${CF_FILENAME_MATCHER}
      ENABLE_RCON: "true"
    env_file:
      - .env
      - .${PROJECT_NAME}.env
    volumes:
      - ./${PROJECT_NAME}/mc-data:/data
  backup:
    image: itzg/mc-backup
    container_name: ${PROJECT_NAME}-backup
    profiles:
      - backup
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_HOSTNAME: ${PROJECT_NAME}
      RESTIC_REPOSITORY: rclone:SUPABASE:mc-server/${PROJECT_NAME}
      RCLONE_LOG_LEVEL: ERROR
    env_file:
      - .env
      - .${PROJECT_NAME}.env
    volumes:
      - ./${PROJECT_NAME}/mc-data:/data:ro
      - ./${PROJECT_NAME}/backups:/backups
